CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(30) NOT NULL,
    compliance_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    rating NUMERIC(3, 2) NOT NULL DEFAULT 0.00,
    CONSTRAINT chk_user_role CHECK (role IN ('FREIGHT_OWNER', 'TRANSPORTER', 'ADMIN')),
    CONSTRAINT chk_user_compliance CHECK (compliance_status IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT chk_user_rating CHECK (rating >= 0 AND rating <= 5)
);

CREATE TABLE compliance_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    document_type VARCHAR(50) NOT NULL,
    document_reference VARCHAR(255) NOT NULL,
    submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    reviewed_at TIMESTAMP,
    CONSTRAINT fk_compliance_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT chk_document_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

CREATE TABLE cargo_loads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    origin VARCHAR(100) NOT NULL,
    destination VARCHAR(100) NOT NULL,
    cargo_type VARCHAR(50) NOT NULL,
    weight NUMERIC(10, 2) NOT NULL,
    volume NUMERIC(10, 2) NOT NULL,
    pickup_start TIMESTAMP NOT NULL,
    pickup_end TIMESTAMP NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    CONSTRAINT fk_load_owner FOREIGN KEY (owner_id) REFERENCES users(id),
    CONSTRAINT chk_load_weight CHECK (weight > 0),
    CONSTRAINT chk_load_volume CHECK (volume > 0),
    CONSTRAINT chk_load_window CHECK (pickup_end > pickup_start),
    CONSTRAINT chk_load_status
        CHECK (status IN ('OPEN', 'MATCHED', 'IN_TRANSIT', 'COMPLETED', 'CANCELLED'))
);

CREATE TABLE trucks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transporter_id BIGINT NOT NULL,
    type VARCHAR(30) NOT NULL,
    capacity NUMERIC(10, 2) NOT NULL,
    current_location VARCHAR(100) NOT NULL,
    availability_start TIMESTAMP NOT NULL,
    availability_end TIMESTAMP NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'AVAILABLE',
    CONSTRAINT fk_truck_transporter FOREIGN KEY (transporter_id) REFERENCES users(id),
    CONSTRAINT chk_truck_capacity CHECK (capacity > 0),
    CONSTRAINT chk_truck_window CHECK (availability_end > availability_start),
    CONSTRAINT chk_truck_type CHECK (type IN ('FLATBED', 'BOX_TRUCK', 'REFRIGERATED', 'TANKER')),
    CONSTRAINT chk_truck_status CHECK (status IN ('AVAILABLE', 'MATCHED', 'IN_TRANSIT', 'UNAVAILABLE'))
);

CREATE TABLE matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    load_id BIGINT NOT NULL,
    truck_id BIGINT NOT NULL,
    score NUMERIC(5, 2) NOT NULL,
    reasons VARCHAR(1000) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PROPOSED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_match_load FOREIGN KEY (load_id) REFERENCES cargo_loads(id),
    CONSTRAINT fk_match_truck FOREIGN KEY (truck_id) REFERENCES trucks(id),
    CONSTRAINT chk_match_score CHECK (score >= 0 AND score <= 100),
    CONSTRAINT chk_match_status CHECK (status IN ('PROPOSED', 'ACCEPTED', 'REJECTED')),
    CONSTRAINT uk_match_load_truck UNIQUE (load_id, truck_id)
);

CREATE TABLE receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id VARCHAR(36) NOT NULL UNIQUE,
    match_id BIGINT NOT NULL UNIQUE,
    actor_id BIGINT NOT NULL,
    decision VARCHAR(20) NOT NULL,
    decided_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ip_address VARCHAR(45),
    user_agent VARCHAR(500),
    CONSTRAINT fk_receipt_match FOREIGN KEY (match_id) REFERENCES matches(id),
    CONSTRAINT fk_receipt_actor FOREIGN KEY (actor_id) REFERENCES users(id),
    CONSTRAINT chk_receipt_decision CHECK (decision IN ('ACCEPTED', 'REJECTED'))
);

CREATE TABLE tracking_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT NOT NULL,
    status VARCHAR(40) NOT NULL,
    latitude NUMERIC(9, 6),
    longitude NUMERIC(9, 6),
    recorded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tracking_match FOREIGN KEY (match_id) REFERENCES matches(id),
    CONSTRAINT chk_tracking_status CHECK (
        status IN ('ACCEPTED', 'DRIVER_ASSIGNED', 'EN_ROUTE_TO_PICKUP', 'CARGO_COLLECTED',
                   'IN_TRANSIT', 'DELIVERED', 'COMPLETED')
    ),
    CONSTRAINT chk_tracking_latitude CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
    CONSTRAINT chk_tracking_longitude CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180)
);

CREATE TABLE ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT NOT NULL,
    reviewer_id BIGINT NOT NULL,
    reviewed_user_id BIGINT NOT NULL,
    score INTEGER NOT NULL,
    comment VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_rating_match FOREIGN KEY (match_id) REFERENCES matches(id),
    CONSTRAINT fk_rating_reviewer FOREIGN KEY (reviewer_id) REFERENCES users(id),
    CONSTRAINT fk_rating_reviewed_user FOREIGN KEY (reviewed_user_id) REFERENCES users(id),
    CONSTRAINT chk_rating_score CHECK (score BETWEEN 1 AND 5),
    CONSTRAINT uk_rating_match_reviewer UNIQUE (match_id, reviewer_id)
);

CREATE TABLE disputes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT NOT NULL,
    creator_id BIGINT NOT NULL,
    reason VARCHAR(1000) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_dispute_match FOREIGN KEY (match_id) REFERENCES matches(id),
    CONSTRAINT fk_dispute_creator FOREIGN KEY (creator_id) REFERENCES users(id),
    CONSTRAINT chk_dispute_status CHECK (status IN ('OPEN', 'UNDER_REVIEW', 'RESOLVED', 'REJECTED'))
);

CREATE TABLE audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id BIGINT,
    action VARCHAR(100) NOT NULL,
    entity_type VARCHAR(100) NOT NULL,
    entity_id VARCHAR(100) NOT NULL,
    metadata VARCHAR(2000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_actor FOREIGN KEY (actor_id) REFERENCES users(id)
);

CREATE INDEX idx_compliance_user ON compliance_documents(user_id);
CREATE INDEX idx_load_owner ON cargo_loads(owner_id);
CREATE INDEX idx_load_origin_status ON cargo_loads(origin, status);
CREATE INDEX idx_truck_transporter ON trucks(transporter_id);
CREATE INDEX idx_truck_location_status ON trucks(current_location, status);
CREATE INDEX idx_match_load ON matches(load_id);
CREATE INDEX idx_match_truck ON matches(truck_id);
CREATE INDEX idx_match_status ON matches(status);
CREATE INDEX idx_tracking_match ON tracking_events(match_id);
CREATE INDEX idx_dispute_status ON disputes(status);
CREATE INDEX idx_audit_entity ON audit_events(entity_type, entity_id);
CREATE INDEX idx_audit_created_at ON audit_events(created_at);
